### ISSUE TITLE
migrate docker image to gcr.io/cloudflare-registry with multi-arch support

### ISSUE THREAD

**Issue by mattalberts** [cloudflare/cloudflare-ingress-controller#56]
Migrate the docker image to an alternate docker repository and provide multi-arch support.
```
image: "gcr.io/cloudflare-registry/argo-tunnel:0.5.2"
```
> **tip**: the published manifest allows docker to select the architecture

**Task List**:
- [ ] rename repository name `argot` ---> `argo-tunnel`
- [ ] update helm chart values `./chart/values.yaml`
- [ ] update pre-built manifest `./deploy/argo-tunnel.yaml`
- [ ] update pre-built manifest `./deploy/argo-tunnel-no-rbac.yaml`
- [ ] add repository `argo-tunnel-amd64`
- [ ] add repository `argo-tunnel-arm64v8`
- [ ] add repository `argo-tunnel-ppc64le`
- [ ] add manifest `argo-tunnel`
